[bumpver]
current_version = "0.8.2"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"src/vector_inspector/__init__.py" = [
    '__version__ = "{version}"'
]
"pyproject.toml" = [
    'version = "{version}"',
]
